### ISSUE TITLE
[Question] Kodery.com no longer work?

### ISSUE THREAD

**Issue by Kristinita** [kodery/blog.kodery.com#1]
In [kodery.com](http://kodery.com/) page I click to link `Register here...` → on <http://account.kodery.com/register> page I saw:

> Heroku | No such app

>There is no app configured at that hostname.
>Perhaps the app owner has renamed it, or you mistyped the URL.

![Kodery](http://i.imgur.com/QSelCyf.png)

Will be work Kodery.com?

Thanks.

**Comment by PaulAdamDavis** [comment]
Hi @Kristinita :) Thanks for your interest in Kodery!

This version of Kodery is no longer in development. There is an older version which is slowly being worked on, but isn't accepting new users at the moment. Your best bet is to follow [@kodery](https://twitter.com/kodery) on Twitter where any news will be published.
